### ISSUE TITLE
Mail from address not working in Plone 5

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#17]
Follow the discussion here https://github.com/quintagroup/collective.easyform/issues/33

**Comment by tomgross** [comment]
Fixed here: https://github.com/collective/collective.easyform/commit/7f2b14c85723e3812aff4f014afc948fdbda4274

**Comment by prakharjoshi** [comment]
Thanks. Missed that branch while creating the issue :)

**Comment by tomgross** [comment]
@prakharjoshi Thanks for picking that up all together. The branch also contains a buildout config for Plone 5

**Comment by prakharjoshi** [comment]
@tomgross  Thanks for pointing this things. I was messing with master branch and changed the whole bootstrap script and buildouts to work according to plone 5 but got a lot of version conflicts. Let me again build the site with this branch. And yeah I will try to finish all these things in this years project.

**Comment by prakharjoshi** [comment]
I am still not able to create a new form with mailer action on as it is still showing me errors like http://pastebin.com/ewXHuR4H . After I made the following changes as suggested above. :(

**Comment by prakharjoshi** [comment]
Okay, its now working for me, I need to change the mailer template as it was the culprit for the error. I replaced with the PFG mailer template and it worked perfectly. :)

**Comment by prakharjoshi** [comment]
this is fixed.
